ALTER TABLE leads
  ADD COLUMN visitor_id  VARCHAR(36)  DEFAULT NULL,
  ADD COLUMN ip_address  VARCHAR(45)  DEFAULT NULL,
  ADD COLUMN ip_country  VARCHAR(100) DEFAULT NULL,
  ADD COLUMN ip_city     VARCHAR(100) DEFAULT NULL,
  ADD COLUMN ip_isp      VARCHAR(200) DEFAULT NULL,
  ADD COLUMN ip_mobile   TINYINT(1)   DEFAULT 0,
  ADD COLUMN ip_proxy    TINYINT(1)   DEFAULT 0;
